(function(){
var p=location.pathname.replace(/\/$/,''),C={
'/categoria/cartoes-de-visita':['Cartões de visita sem complicação','Escolha o acabamento e compare somente as opções certas.',['Todos','Básico','Frente e verso','Com verniz','PVC','Reciclato']],
'/categoria/banners-e-cartazes':['Banners e cartazes na medida certa','Escolha o material para ver tamanhos e preços.',['Todos','Lona','Photogloss','Sulfite','Offset']],
'/categoria/panfletos-flyers-e-folders':['Panfletos e folders para divulgar','Escolha tamanho ou impressão frente e verso.',['Todos','10x15','10x21','15x21','21x30','Frente e verso']],
'/categoria/dtf':['Qual DTF você precisa?','Escolha tecido ou adesivo UV para superfícies rígidas.',['Todos','DTF UV','DTF Têxtil']],
'/categoria/revelacao-de-fotos':['Fotos e ímãs personalizados','Escolha fotos ou ímãs e vá direto ao produto.',['Todos','Fotos','Ímãs']],
'/categoria/plotagem-de-projetos':['Plotagem de projetos mais fácil','Selecione impressão ou papel para encontrar sua opção.',['Todos','Preto e branco','Colorida','Papel vegetal','Full color']]};
if(!C[p])return;var css='.cpGhide{display:none!important}body.cpGon .vitrine-coluna-esquerda{display:none!important}body.cpGon .vitrine-produto-lista{width:100%!important;max-width:none!important}.cpG,.cpG *{box-sizing:border-box}.cpG{max-width:1240px;margin:24px auto 50px;padding:0 20px;font-family:Arial,sans-serif;color:#172333}.cpGh{padding:30px 36px;border-radius:20px;color:#fff;background:linear-gradient(120deg,#063b80,#1679df);box-shadow:0 12px 30px #084a9c33}.cpGh h1{color:#fff!important;font-size:34px!important;margin:0 0 9px!important}.cpGh p{font-size:16px;margin:0}.cpGp{margin-top:24px;padding:24px;border:1px solid #dce6f0;border-radius:18px;background:#fff}.cpGp h2{margin:0 0 14px;color:#102f59}.cpGf{display:flex;flex-wrap:wrap;gap:10px}.cpGf button{min-height:46px;padding:0 18px;border:2px solid #dbe5ef;border-radius:12px;background:#fff;font-weight:800}.cpGf button.on{border-color:#1267c7;background:#edf6ff;color:#084a9c}.cpGc{margin:22px 0 13px;color:#687789}.cpGg{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.cpGi{display:grid;grid-template-columns:125px 1fr;min-height:165px;border:1px solid #dce6f0;border-radius:16px;overflow:hidden;background:#fff}.cpGi img{width:125px;height:100%;object-fit:cover}.cpGx{padding:16px;display:flex;flex-direction:column}.cpGx h3{font-size:15px;color:#102f59;margin:0 0 8px}.cpGprice{margin:auto 0 11px;font-weight:900;color:#084a9c}.cpGgo{display:flex!important;min-height:40px;align-items:center;justify-content:center;border-radius:9px;background:#1267c7;color:#fff!important;text-decoration:none!important;font-size:12px;font-weight:900}@media(max-width:900px){.cpGg{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.cpG{padding:0 12px}.cpGh{padding:23px}.cpGh h1{font-size:27px!important}.cpGg{grid-template-columns:1fr}.cpGf button{flex:1 1 40%}}';var st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function n(v){return(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim()}function tag(t){t=n(t);if(p.indexOf('cartoes')>0){if(t.indexOf('pvc')>=0)return'PVC';if(t.indexOf('recicl')>=0)return'Reciclato';if(t.indexOf('verniz')>=0&&t.indexOf('sem verniz')<0)return'Com verniz';if(t.indexOf('frente e verso')>=0)return'Frente e verso';return'Básico'}if(p.indexOf('banners')>0){if(t.indexOf('photogloss')>=0)return'Photogloss';if(t.indexOf('sulfite')>=0)return'Sulfite';if(t.indexOf('off-set')>=0||t.indexOf('offset')>=0)return'Offset';return'Lona'}if(p.indexOf('panfletos')>0){if(t.indexOf('frente e verso')>=0)return'Frente e verso';for(var z of ['10x15','10x21','15x21','21x30'])if(t.indexOf(z)>=0)return z;return'Outros'}if(p.indexOf('/dtf')>0)return t.indexOf('uv')>=0?'DTF UV':'DTF Têxtil';if(p.indexOf('revelacao')>0)return t.indexOf('ima')>=0?'Ímãs':'Fotos';if(p.indexOf('plotagem')>0){if(t.indexOf('vegetal')>=0)return'Papel vegetal';if(t.indexOf('preenchimento')>=0||t.indexOf('full color')>=0)return'Full color';if(t.indexOf('preto e branco')>=0)return'Preto e branco';return'Colorida'}return'Outros'}
function run(){if(document.querySelector('.cpG'))return;var content=document.querySelector('#conteudo-corpo,.conteudo-corpo');if(!content)return;var seen={},items=[];document.querySelectorAll('a[href*="/produto/"]').forEach(function(a){if(seen[a.href])return;seen[a.href]=1;var par=a.closest('li,.produto,.vitrine-produto,.box-3,.box-4')||a,text=(par.innerText||a.innerText||'');if(text.length<5)return;var im=par.querySelector('img'),price=(text.match(/R\$\s*[\d\.]+,\d{2}/)||[])[0]||'Consulte',title=(a.getAttribute('help')||a.title||a.innerText||text).trim();items.push({u:a.href,t:title,i:im&&im.src,p:price,g:tag(text)})});if(!items.length)return;var box=document.createElement('section'),cfg=C[p];box.className='cpG';box.innerHTML='<div class="cpGh"><h1>'+cfg[0]+'</h1><p>'+cfg[1]+'</p></div><div class="cpGp"><h2>O que você procura?</h2><div class="cpGf">'+cfg[2].map(function(x,i){return'<button data-g="'+x+'" class="'+(i?'':'on')+'">'+x+'</button>'}).join('')+'</div></div><p class="cpGc"></p><div class="cpGg"></div>';function draw(g){var L=g==='Todos'?items:items.filter(function(x){return x.g===g});box.querySelector('.cpGc').textContent=L.length+' opções encontradas';box.querySelector('.cpGg').innerHTML=L.map(function(x){return'<article class="cpGi">'+(x.i?'<img src="'+x.i+'" alt="">':'')+'<div class="cpGx"><h3>'+x.t+'</h3><div class="cpGprice">'+x.p+'</div><a class="cpGgo" href="'+x.u+'">ESCOLHER →</a></div></article>'}).join('')}box.onclick=function(e){var b=e.target.closest('[data-g]');if(!b)return;box.querySelectorAll('button').forEach(function(q){q.classList.remove('on')});b.classList.add('on');draw(b.dataset.g)};content.insertBefore(box,content.firstChild);Array.from(content.children).forEach(function(x){if(x!==box)x.classList.add('cpGhide')});document.body.classList.add('cpGon');draw('Todos')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();setTimeout(run,700)
})();
